# -*- coding: utf-8 -*-
"""CNN_Fashion_MNIST

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zkL5L6-W7B4EPb0DLtuSmsj4vEtdtpAF
"""

import tensorflow as tf
from future import *
import tensorflow_datasets as tfds
tf.logging.set_verbosity(tf.logging.ERROR)
import math
import matplotlib as plt
import numpy as np
import tqdm
import tqdm.auto
tqdm.tqdm=tqdm.auto.tqdm
#print(tf.__version__)
tf.enable_eager_execution()